// Package generator provides code stub generation from OpenAPI specs.
package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/EdgarOrtegaRamirez/apicontract/internal/parser"
)

// Format represents a code generation format.
type Format string

const (
	FormatGo       Format = "go"
	FormatPython   Format = "python"
	FormatTypeScript Format = "typescript"
)

// Generate creates code stubs from an OpenAPI spec.
func Generate(spec *parser.Spec, format Format) (string, error) {
	switch format {
	case FormatGo:
		return generateGo(spec)
	case FormatPython:
		return generatePython(spec)
	case FormatTypeScript:
		return generateTypeScript(spec)
	default:
		return "", fmt.Errorf("unsupported format: %s", format)
	}
}

// generateGo creates Go client stubs.
func generateGo(spec *parser.Spec) (string, error) {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("// Generated client stub for %s v%s\n", spec.Info.Title, spec.Info.Version))
	sb.WriteString("// This file was auto-generated by apicontract\n\n")

	sb.WriteString("package client\n\n")
	sb.WriteString("import (\n")
	sb.WriteString("\t\"net/http\"\n")
	sb.WriteString("\t\"time\"\n")
	sb.WriteString(")\n\n")

	sb.WriteString("// Client is the auto-generated API client.\n")
	sb.WriteString("type Client struct {\n")
	sb.WriteString("\tBaseURL string\n")
	sb.WriteString("\tHTTPClient *http.Client\n")
	sb.WriteString("}\n\n")

	sb.WriteString("// NewClient creates a new API client.\n")
	sb.WriteString("func NewClient(baseURL string) *Client {\n")
	sb.WriteString("\treturn &Client{\n")
	sb.WriteString("\t\tBaseURL:    baseURL,\n")
	sb.WriteString("\t\tHTTPClient: &http.Client{Timeout: 30 * time.Second},\n")
	sb.WriteString("\t}\n")
	sb.WriteString("}\n\n")

	for _, path := range sortedMapKeys(spec.Paths) {
		pathItem := spec.Paths[path]
		for _, method := range sortedMapKeys(pathItem.Operations) {
			op := pathItem.Operations[method]
			if op.OperationID == "" {
				continue
			}
			funcName := toGoName(op.OperationID)
			sb.WriteString(fmt.Sprintf("// %s performs a %s request to %s.\n", funcName, method, path))
			sb.WriteString(fmt.Sprintf("func (c *Client) %s() error {\n", funcName))
			sb.WriteString(fmt.Sprintf("\turl := c.BaseURL + %q\n", path))
			sb.WriteString(fmt.Sprintf("\treq, err := http.NewRequest(%q, url, nil)\n", strings.ToUpper(method)))
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			sb.WriteString("\tresp, err := c.HTTPClient.Do(req)\n")
			sb.WriteString("\tif err != nil {\n")
			sb.WriteString("\t\treturn err\n")
			sb.WriteString("\t}\n")
			sb.WriteString("\tdefer resp.Body.Close()\n")
			sb.WriteString("\treturn nil\n")
			sb.WriteString("}\n\n")
		}
	}

	return sb.String(), nil
}

// generatePython creates Python client stubs.
func generatePython(spec *parser.Spec) (string, error) {
	var sb strings.Builder

	sb.WriteString("'''Auto-generated client for " + spec.Info.Title + " v" + spec.Info.Version + "'''\n")
	sb.WriteString("from __future__ import annotations\n\n")
	sb.WriteString("import httpx\n\n")

	sb.WriteString("class Client:\n")
	sb.WriteString("    \"\"\"Auto-generated API client.\"\"\"\n\n")
	sb.WriteString("    def __init__(self, base_url: str) -> None:\n")
	sb.WriteString("        self.base_url = base_url\n")
	sb.WriteString("        self.client = httpx.Client(timeout=30.0)\n\n")

	for _, path := range sortedMapKeys(spec.Paths) {
		pathItem := spec.Paths[path]
		for _, method := range sortedMapKeys(pathItem.Operations) {
			op := pathItem.Operations[method]
			if op.OperationID == "" {
				continue
			}
			funcName := toPythonName(op.OperationID)
			sb.WriteString("    def " + funcName + "(self) -> httpx.Response:\n")
			sb.WriteString("        \"\"\"Perform " + method + " " + path + ".\"\"\"\n")
			sb.WriteString("        url = f\"{self.base_url}" + path + "\"\n")
			sb.WriteString("        return self.client.request(\"" + strings.ToUpper(method) + "\", url)\n\n")
		}
	}

	return sb.String(), nil
}

// generateTypeScript creates TypeScript client stubs.
func generateTypeScript(spec *parser.Spec) (string, error) {
	var sb strings.Builder

	sb.WriteString("// Auto-generated client for " + spec.Info.Title + " v" + spec.Info.Version + "\n")
	sb.WriteString("// This file was auto-generated by apicontract\n\n")

	sb.WriteString("export class Client {\n")
	sb.WriteString("  private baseUrl: string\n")
	sb.WriteString("  constructor(baseUrl: string) {\n")
	sb.WriteString("    this.baseUrl = baseUrl\n")
	sb.WriteString("  }\n\n")

	for _, path := range sortedMapKeys(spec.Paths) {
		pathItem := spec.Paths[path]
		for _, method := range sortedMapKeys(pathItem.Operations) {
			op := pathItem.Operations[method]
			if op.OperationID == "" {
				continue
			}
			funcName := toTSName(op.OperationID)
			sb.WriteString("  async " + funcName + "(): Promise<Response> {\n")
			sb.WriteString("    const url = `${this.baseUrl}" + path + "`\n")
			sb.WriteString("    return fetch(url, { method: '" + strings.ToUpper(method) + "' })\n")
			sb.WriteString("  }\n\n")
		}
	}

	sb.WriteString("}\n")
	return sb.String(), nil
}

// toGoName converts a string to a Go-identifiable name.
func toGoName(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(p)
		} else {
			parts[i] = strings.Title(p)
		}
	}
	return strings.Join(parts, "")
}

// toPythonName converts a string to a Python-identifiable name.
func toPythonName(s string) string {
	return strings.ReplaceAll(s, "-", "_")
}

// toTSName converts a string to a TypeScript-identifiable name.
func toTSName(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if i == 0 {
			parts[i] = strings.ToLower(p)
		} else {
			parts[i] = strings.Title(p)
		}
	}
	return strings.Join(parts, "")
}

// sortedMapKeys returns sorted keys from any map[string]T.
func sortedMapKeys[K ~string, V any](m map[K]V) []K {
	keys := make([]K, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return keys[i] < keys[j] })
	return keys
}
